apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-metrics
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fintech-metrics
  template:
    metadata:
      labels:
        app: fintech-metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8086"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: fintech-metrics
        image: akhil774/fintech-metrics:latest
        ports:
        - containerPort: 8086
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fintech-metrics-service
spec:
  type: LoadBalancer
  selector:
    app: fintech-metrics
  ports:
  - port: 8087
    targetPort: 8086
